### ISSUE TITLE
No module named 'dbus'

### ISSUE THREAD

**Issue by leonm1** [qzed/linux-surfacegen5-dtx-daemon#2]
```Traceback (most recent call last):
  File "/opt/surface-dtx/surface-dtx-daemon/.bootstrap/pex/pex.py", line 352, in execute
  File "/opt/surface-dtx/surface-dtx-daemon/.bootstrap/pex/pex.py", line 284, in _wrap_coverage
  File "/opt/surface-dtx/surface-dtx-daemon/.bootstrap/pex/pex.py", line 315, in _wrap_profiling
  File "/opt/surface-dtx/surface-dtx-daemon/.bootstrap/pex/pex.py", line 397, in _execute
  File "/opt/surface-dtx/surface-dtx-daemon/.bootstrap/pex/pex.py", line 495, in execute_entry
  File "/opt/surface-dtx/surface-dtx-daemon/.bootstrap/pex/pex.py", line 509, in execute_pkg_resources
  File "/opt/surface-dtx/surface-dtx-daemon/.bootstrap/pex/vendor/_vendored/setuptools/pkg_resources/__init__.py", line 2384, in resolve
  File "/home/{username}/.pex/install/surface_dtx-0.1.4-py3-none-any.whl.40286961a8faf8f785429536b47d769f13809031/surface_dtx-0.1.4-py3-none-any.whl/surface_dtx/daemon.py", line 5, in <module>
    from . import notify
  File "/home/{username}/.pex/install/surface_dtx-0.1.4-py3-none-any.whl.40286961a8faf8f785429536b47d769f13809031/surface_dtx-0.1.4-py3-none-any.whl/surface_dtx/notify.py", line 7, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```
After installing from the PKGBUILD on Artix (AUR-compatible Arch derivative with runit as init system)), I can neither run the program as a service nor by directly executing the executable in /opt/surface-dtx

**Comment by qzed** [comment]
I should have noticed that during testing, sorry for the inconvenience and thanks for reporting! Not sure how I managed to get it working in the first place, but I can reproduce this issue with a new virtualenv and cleaned pex cache (`rm -rf ~/.pex`). It looks like I screwed up the dependencies in `setup.py`, I'm still testing to make sure this is it, though.

**Comment by qzed** [comment]
Okay, the PKGBUILD in `master` should work now. Let me know if there are any issues!
